name: Deploy IIS

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet Packages
        run: nuget restore GithubActionWithIIS.sln
        
      - name: Build and Publish
        shell: cmd
        run: |
          cd GithubActionWithIIS
          msbuild /t:rebuild /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=PublishProfile

  deploy-webapp-01:
    needs: build
    name: Deploy 01
    runs-on: self-hosted
    steps:

      - name: Deploy to IIS
        run: |
          stop-webapppool WebApplication
          stop-iissite -Name WebApplication -Confirm: $false
          Copy-Item C:/temp/WebApplication/deploy/* C:/WEBDATA/WebApplication/webapp-1 -Recurse -Force
          start-webapppool WebApplication
          start-iissite WebApplication


  deploy-webapp-02:
    needs: build
    name: Deploy 02
    runs-on: self-hosted
    steps:

      - name: Deploy to IIS
        run: |
          stop-webapppool WebApplication
          stop-iissite -Name WebApplication -Confirm: $false
          Copy-Item C:/temp/WebApplication/deploy/* C:/WEBDATA/WebApplication/webapp-2 -Recurse -Force
          start-webapppool WebApplication
          start-iissite WebApplication
